#the layer sizes get translated to [input_size, layer1_size, layer2_size, output_size] in the config
layer1_size:
  type: "int"
  range: [32, 256]

layer2_size:
  type: "int"
  range: [32, 256]

#this gets translated to [1.0-a, 1.0+a] in the config
time_scale_augmentation:
  type: "float"
  range: [0.01, 0.5]
  log: true

lr:
  type: "float"
  range: [0.0001, 0.01] 
  log: true

weight_scale: #before i run this, let's check what is going on by making small networks without readout heads
  type: "float"
  range: [0.1, 2.0]
  log: true

surrogate_alpha:
  type: "float"
  range: [1.0, 10.0]
  log: true

grad_clip_value:
  type: "float"
  range: [2.0, 10.0]
  log: true

weight_decay:
  type: "float"
  range: [0.00001, 0.1]
  log: true

